// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqQEBkKrONGJvufR9F-tgU7VUTKqpVy8k',
    appId: '1:1062495598488:web:12a7f964ce69d6d2315ded',
    messagingSenderId: '1062495598488',
    projectId: 'rajputji0',
    authDomain: 'rajputji0.firebaseapp.com',
    storageBucket: 'rajputji0.firebasestorage.app',
    measurementId: 'G-P54S8FXF4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbS76xXixYk475FkP_LWQ2V4Kxq5tkJhA',
    appId: '1:1062495598488:android:aa27d35baf1c7b81315ded',
    messagingSenderId: '1062495598488',
    projectId: 'rajputji0',
    storageBucket: 'rajputji0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN7cq5Tv9mMiE_G51w1PTuSiwclE7JB2A',
    appId: '1:1062495598488:ios:c5a67267dcd1b6cc315ded',
    messagingSenderId: '1062495598488',
    projectId: 'rajputji0',
    storageBucket: 'rajputji0.firebasestorage.app',
    iosBundleId: 'com.example.noproxys1',
  );

}